# Generated by Django 3.0.5 on 2020-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('장르', models.CharField(max_length=10)),
                ('제목', models.CharField(max_length=500)),
            ],
        ),
    ]
